### PR TITLE
downgrade the  filemanager-webpack-plugin to 3.1.1

### PR DESCRIPTION
**Pull request by RichardStark**
"filemanager-webpack-plugin": "^6.1.7" uses webpack 5.0.0, which cause conflict with vue-cli, using webpack 4.0.0. and when running npm run server, it will cause  Error: Rule can only have one resource source...

### CODE REVIEW

**Comment by wangcheng26** [comment]
我们本地没有浮现出来这个问题，请提供一下
1、node版本
2、npm安装还是yarn安装
3、是否直接clone我们的项目安装的依赖
谢谢

**Comment by RichardStark** [comment]
The error is caused by npm version, if you have ever found the notice `npm i -g npm` and executed it, be careful that the build will success in npm 6.x.x and 7.x.x(8.x.x build will cause another error), but only 6.x.x can resolve correctly,  7.x.x will cause error in `npm run serve`

**Comment by RichardStark** [comment]
Just work well after executing `npm i -g npm@6.14.14`

**Comment by githubnameting** [comment]
npm 版本问题 建议使用 npm6 node 14

**Pull request closed without merging**
